### ISSUE TITLE
Release Todo

### ISSUE THREAD

**Issue by JoFrhwld** [Forced-Alignment-and-Vowel-Extraction/alignedTextGrid#150]
- [x] Bump version number

```
poetry version minor
```

- [x] Commit version bump, add and push git tag 

```
git commit -am "Version bump"
git tag -a v0.5.0
git pull
git push --tags
```

- [x] Open PR to `main`
- [x] Pull, build, and publish from `main`

```
git checkout main
git pull
poetry build
poetry publish
```
